"""Change constraint type to nullable

Revision ID: 7ce9ee3743ad
Revises: 179fde6212d5
Create Date: 2023-09-09 09:52:58.211336

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7ce9ee3743ad'
down_revision = '179fde6212d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variable', 'constraint_type',
               existing_type=postgresql.ENUM('range', 'list', name='variableconstraintenum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('variable', 'constraint_type',
               existing_type=postgresql.ENUM('range', 'list', name='variableconstraintenum'),
               nullable=False)
    # ### end Alembic commands ###
