"""Add unique constraint to variable model

Revision ID: 884e9f397907
Revises: 7ce9ee3743ad
Create Date: 2023-09-09 10:00:13.537898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '884e9f397907'
down_revision = '7ce9ee3743ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('_variable_name_in_formula', 'variable', ['name', 'formula_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('_variable_name_in_formula', 'variable', type_='unique')
    # ### end Alembic commands ###
